#DATADICTION

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere



## BASIC PYTHON


Question-Write a Python function named slope_of_cubic that calculates the slope of a cubic polynomial based on user input. The function should:
1. Accepts two arguments:

* A tuple containing 4 real numbers which are the coefficients of the cubic term, quadratic term, linear term, and constant term respectively.

* A real number which is the value of x at which the slope has to be calculated.

2. Returns the slope of the cubic polynomial at the given value of x.

In [ ]:
def slope_of_cubic(coffs, x):

  p, q, r, s = coffs

  slope = 3*p*x**2 + 2*q*x + r #derivative of px^3+qx^2+rx+s

  return slope

##NumPy (Numerical Python)
###Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of ndarray

In [ ]:
import numpy as np

In [23]:
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# Write a NumPy function to create an array with random values of shape [3,4]

from numpy import random

def create_random_arr():

  a = random.rand(3 ,4)
  return a

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def zero_arr():

  a = np.zeros((3, 4))
  return a


In [25]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

def evn_spcd_arr(start, stop, num = 50, endpoint = True, dtype=None):

  return np.linspace(start, stop , num=num, endpoint=endpoint, dtype=dtype)

### Basic array operations
- algebraic operations
- logical operations

In [26]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [27]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def opretions_arr(a, b):

  ans = {
      "add": np.add(a, b),
      "subtract": np.subtract(a, b),
      "product": np.multiply(a, b),
      "division": np.divide(a, b)
  }

  return ans

In [28]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
def sum_ovr_axis0(a, b):

  new_arr = np.sum([a, b], axis=0)

  return new_arr
# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum_ovr_axis1(a, b):

  new_arr = np.sum([a, b], axis=1)

  return new_arr

In [29]:
# Write a NumPy function to reverse the array 'a'
def rev_arr(a):

  new_arr = a[::-1, ::-1]
  return new_arr
# Write a NumPy function to reverse the array 'a' along axis=0
def rev_arr_axis0(a):

  new_arr = a[::-1, :]
  return new_arr
# Write a NumPy function to reverse the array 'a' along axis=1
def rev_arr_axis1(a):

  new_arr = a[:, ::-1]
  return new_arr

### Sorting and concatenation
- sort arrays
- join multiple arrays

In [30]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [31]:
# Write a NumPy function to sort the array 'a'
def sort_arr(a):
  return np.sort(a)

# Write a NumPy function to sort the array 'a' along axis=0
def sort_arr_axis0(a):
  return np.sort(a, axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
def sort_arr_axis1(a):
  return np.sort(a, axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sort_arr_dscn_axis0(a):
  return np.sort(a, axis=0)[::-1]


In [32]:
# Write a NumPy function to argsort the array along axis=0
def argsort_arr_axis0(a):
  return np.argsort(a, axis=0)

# Write a NumPy function to argsort the array along axis=1
def argsort_arr_axis1(a):
  return np.argsort(a, axis=1)


In [33]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concatenate_arr(a, b):
  arr = np.concatenate((a, b))
  return arr

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concatenate_arr_axis0(a, b):
  arr = np.concatenate((a, b), axis=0)
  return arr

# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array


In [34]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [35]:
# Write a NumPy function to get the Number of dimensions
def no_of_dimension(a):
  return a.ndim

# Write a NumPy function to get the Shape of the array
def shape_arr(a):
  return a.shape

# Write a NumPy function to get the Size of the array
def size_arr(a):
  return a.size

In [36]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape_arr(a):
  return a.reshape(1, 9)

In [37]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
def add_axis(a):
  new_arr1 = a[np.newaxis, :]

  new_arr2 = a.reshape(1, 3, 3)

  return new_arr1, new_arr2

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [38]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [39]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
def arr_index_and_slice(a):
  #inexing by an integer
  i = a[2]

  #indexing by a tuple
  t = a[(2, 2)]

  #indexing using a range
  r = a[0:2, 0:2]

  return i,t,r

In [40]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
def values_greater_than_4(a):
  condition = a > 4
  values = a[condition]
  return values

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def values_multiple_conditions(a):
  condition = (a > 4) & (a%2 == 0)
  values = a[condition]
  return values

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [41]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [42]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def copy_arr(a):
  arr = a.copy()
  arr+=1
  return arr

ans = copy_arr(a)
print(ans)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.


#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [43]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd

df = pd.DataFrame(iris_2d)
new_df = df.dropna()

In [ ]:
import pandas as pd

# Assuming df is already defined from previous cells
# Write a Pandas function to find the mean, median and standard deviation of column 3.

mean_col3 = df[2].mean()
median_col3 = df[2].median()
std_col3 = df[2].std()

mean_col3, median_col3, std_col3

(np.float64(3.758666666666666), 4.35, 1.7644204199522617)

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
correlation = df[0].corr(df[1])
correlation

np.float64(-0.10936924995064937)

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

sepal_length = df[0]
petal_length = df[2]

volume = (np.pi * petal_length * (sepal_length ** 2)) / 3

df['volume'] = volume

### Miscellaneous

Q1 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [44]:
from numpy import random

x = random.randint(10, size=(2, 5))
print(x)

max_val = np.max(x, axis=1)
min_val = np.min(x, axis=1)

max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("Max Values:", max_val)
print("Max Indices:", max_indices)
print("Min Values:", min_val)
print("Min Indices:", min_indices)

[[1 5 5 1 9]
 [2 9 9 7 5]]
Max Values: [9 9]
Max Indices: [4 1]
Min Values: [1 2]
Min Indices: [0 0]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [45]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
p, q, r = np.split(x, [4, 6])

print(p)
print(q)
print(r)

[1 2 3 4]
[5 6]
[7 8 9]


### PANDAS

Run the following cell before proceeding further


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q3- Write a Pandas function to find the count of unique species.

In [ ]:
def unique_species_count(df):
  return df['species'].nunique()

# Q4 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
def bin_petal_len(df):
  pd.cut(
      df[2],
      bins = [-float("inf"), 3, 5, float("inf")],
      labels = ['small', 'medium', 'large'],
      right = False
      )

Q5 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
def most_freq_petal_len(df):
  return df[2].mode()[0]